#![doc = "Peripheral access API for MSPM0L222X microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
pub use cortex_m::peripheral::Peripherals as CorePeripherals;
pub use cortex_m::peripheral::{CBP, CPUID, DCB, DWT, FPB, ITM, MPU, NVIC, SCB, SYST, TPIU};
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {
    fn INT_GROUP0();
    fn INT_GROUP1();
    fn UART0();
    fn UART1();
    fn AESADV();
    fn DMA0();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(link_section = ".vector_table.interrupts")]
#[unsafe(no_mangle)]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector {
        _handler: INT_GROUP0,
    },
    Vector {
        _handler: INT_GROUP1,
    },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: UART0 },
    Vector { _handler: UART1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: AESADV },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: DMA0 },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - SYSCTL interrupt (group 0, IIDX 6)"]
    INT_GROUP0 = 0,
    #[doc = "1 - GPIOC interrupt (group 1, IIDX 6)"]
    INT_GROUP1 = 1,
    #[doc = "15 - UART0"]
    UART0 = 15,
    #[doc = "16 - UART1"]
    UART1 = 16,
    #[doc = "28 - AESADV"]
    AESADV = 28,
    #[doc = "31 - DMA0"]
    DMA0 = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "DSSM"]
pub type Debugss = crate::Periph<debugss::RegisterBlock, 0x400c_7000>;
impl core::fmt::Debug for Debugss {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Debugss").finish()
    }
}
#[doc = "DSSM"]
pub mod debugss;
#[doc = "WWDT"]
pub type Wwdt0 = crate::Periph<wwdt0::RegisterBlock, 0x4008_0000>;
impl core::fmt::Debug for Wwdt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt0").finish()
    }
}
#[doc = "WWDT"]
pub mod wwdt0;
#[doc = "PERIPHERALREGION"]
pub type Eventlp = crate::Periph<eventlp::RegisterBlock, 0x400c_9000>;
impl core::fmt::Debug for Eventlp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Eventlp").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod eventlp;
#[doc = "PERIPHERALREGION"]
pub type Uart0 = crate::Periph<uart0::RegisterBlock, 0x4010_8000>;
impl core::fmt::Debug for Uart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart0;
#[doc = "PERIPHERALREGION"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x400a_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod gpioa;
#[doc = "PERIPHERALREGION"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x400f_0000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod i2c0;
#[doc = "PERIPHERALREGION"]
pub type Keystorectl = crate::Periph<keystorectl::RegisterBlock, 0x400a_c000>;
impl core::fmt::Debug for Keystorectl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Keystorectl").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod keystorectl;
#[doc = "PERIPHERALREGION"]
pub type Trng = crate::Periph<trng::RegisterBlock, 0x4044_4000>;
impl core::fmt::Debug for Trng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Trng").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod trng;
#[doc = "FACTORYREGION"]
pub type Factoryregion = crate::Periph<factoryregion::RegisterBlock, 0x41c4_0000>;
impl core::fmt::Debug for Factoryregion {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Factoryregion").finish()
    }
}
#[doc = "FACTORYREGION"]
pub mod factoryregion;
#[doc = "PERIPHERALREGION"]
pub type Uart1 = crate::Periph<uart1::RegisterBlock, 0x4010_a000>;
impl core::fmt::Debug for Uart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Uart1").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod uart1;
#[doc = "PERIPHERALREGION"]
pub type Gpiob = crate::Periph<gpiob::RegisterBlock, 0x400a_2000>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod gpiob;
#[doc = "PERIPHERALREGION"]
pub type Gpioc = crate::Periph<gpioc::RegisterBlock, 0x400a_4000>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod gpioc;
#[doc = "NVMNW_GANDALF"]
pub type Flashctl = crate::Periph<flashctl::RegisterBlock, 0x400c_d000>;
impl core::fmt::Debug for Flashctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flashctl").finish()
    }
}
#[doc = "NVMNW_GANDALF"]
pub mod flashctl;
#[doc = "PERIPHERALREGION"]
pub type Aesadv = crate::Periph<aesadv::RegisterBlock, 0x4044_2000>;
impl core::fmt::Debug for Aesadv {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aesadv").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod aesadv;
#[doc = "PERIPHERALREGION"]
pub type Crcp0 = crate::Periph<crcp0::RegisterBlock, 0x4044_0000>;
impl core::fmt::Debug for Crcp0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crcp0").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod crcp0;
#[doc = "PERIPHERALREGION"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4042_a000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod dma;
#[doc = "mem_map"]
pub type Sysctl = crate::Periph<sysctl::RegisterBlock, 0x400a_f000>;
impl core::fmt::Debug for Sysctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctl").finish()
    }
}
#[doc = "mem_map"]
pub mod sysctl;
#[doc = "PERIPHERALREGION"]
pub type Iomux = crate::Periph<iomux::RegisterBlock, 0x4042_8000>;
impl core::fmt::Debug for Iomux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iomux").finish()
    }
}
#[doc = "PERIPHERALREGION"]
pub mod iomux;
#[doc = "CPUSSMMR"]
pub type Cpuss = crate::Periph<cpuss::RegisterBlock, 0x4040_0000>;
impl core::fmt::Debug for Cpuss {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cpuss").finish()
    }
}
#[doc = "CPUSSMMR"]
pub mod cpuss;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "DEBUGSS"]
    pub debugss: Debugss,
    #[doc = "WWDT0"]
    pub wwdt0: Wwdt0,
    #[doc = "EVENTLP"]
    pub eventlp: Eventlp,
    #[doc = "UART0"]
    pub uart0: Uart0,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "KEYSTORECTL"]
    pub keystorectl: Keystorectl,
    #[doc = "TRNG"]
    pub trng: Trng,
    #[doc = "FACTORYREGION"]
    pub factoryregion: Factoryregion,
    #[doc = "UART1"]
    pub uart1: Uart1,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "FLASHCTL"]
    pub flashctl: Flashctl,
    #[doc = "AESADV"]
    pub aesadv: Aesadv,
    #[doc = "CRCP0"]
    pub crcp0: Crcp0,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "SYSCTL"]
    pub sysctl: Sysctl,
    #[doc = "IOMUX"]
    pub iomux: Iomux,
    #[doc = "CPUSS"]
    pub cpuss: Cpuss,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            debugss: unsafe { Debugss::steal() },
            wwdt0: unsafe { Wwdt0::steal() },
            eventlp: unsafe { Eventlp::steal() },
            uart0: unsafe { Uart0::steal() },
            gpioa: unsafe { Gpioa::steal() },
            i2c0: unsafe { I2c0::steal() },
            keystorectl: unsafe { Keystorectl::steal() },
            trng: unsafe { Trng::steal() },
            factoryregion: unsafe { Factoryregion::steal() },
            uart1: unsafe { Uart1::steal() },
            gpiob: unsafe { Gpiob::steal() },
            gpioc: unsafe { Gpioc::steal() },
            flashctl: unsafe { Flashctl::steal() },
            aesadv: unsafe { Aesadv::steal() },
            crcp0: unsafe { Crcp0::steal() },
            dma: unsafe { Dma::steal() },
            sysctl: unsafe { Sysctl::steal() },
            iomux: unsafe { Iomux::steal() },
            cpuss: unsafe { Cpuss::steal() },
        }
    }
}
